### ISSUE TITLE
Docs are pending on Hackage

### ISSUE THREAD

**Issue by expipiplus1** [peti/nix-paths#2]
Hackage seems to have become stuck generating the docs. I think the solution is to manually restart them or manually upload the docs.

**Comment by peti** [comment]
Hackage cannot generate the docs because the configure phase of this package won't succeed unless Nix binaries are installed. If we want docs on Hackage, they must be uploaded. Unfortunately, I have no idea how that works.

**Comment by expipiplus1** [comment]
I think you can do something like `cabal upload --doc` or use this script `https://github.com/ekmett/lens/blob/master/scripts/hackage-docs.sh`

**Comment by peti** [comment]
OK, I didn't know that `cabal` can do this! Thanks for the  pointer! Docs are available online now.

**Comment by expipiplus1** [comment]
you're welcome and thank you!
